Repository Nix-QChem/NixOS-QChem, pull requests merged in 2024-09, with the labels that each got.

#531 Update flake.lock/package list
  flake.lock
Labels: hydra

#533 Update flake.lock/package list
  flake.lock
Labels: hydra

#537 gamess-us: 2023R1P1 -> 2024R2P1
  pkgs/by-name/gamess-us/gcc-config.patch
  pkgs/by-name/gamess-us/openmpi.patch
  pkgs/by-name/gamess-us/package.nix
Labels: package update

#539 Update flake.lock/package list
  flake.lock
  package_list.json
  package_list.md
Labels: hydra

#538 dice: init at unstable-2024-07-02
  nixpkgs-opt.nix
  overlay.nix
  pkgs/by-name/dice/package.nix
Labels: new package

#542 Update flake.lock/package list
  flake.lock
  package_list.json
  package_list.md
Labels: hydra

#543 Update flake.lock/package list
  flake.lock
Labels: hydra

#545 Update flake.lock/package list
  flake.lock
Labels: hydra

#546 Update flake.lock/package list
  flake.lock
Labels: hydra

#549 qmcpack: add utility scripts and python modules
  overlay.nix
  pkgs/by-name/qmcpack/package.nix
  pkgs/python-by-name/qmcpack/package.nix
  pythonPackages.nix
Labels: enhancement

#551 Update flake.lock/package list
  flake.lock
Labels: hydra

#553 Update flake.lock/package list
  flake.lock
Labels: hydra
