Repository Nix-QChem/NixOS-QChem, pull requests merged in 2024-10, with the labels that each got.

#556 Update flake.lock/package list
  flake.lock
Labels: hydra

#557 Update flake.lock/package list
  flake.lock
Labels: hydra

#558 Update flake.lock/package list
  flake.lock
Labels: hydra

#560 Update flake.lock/package list
  flake.lock
Labels: hydra

#562 Update flake.lock/package list
  flake.lock
Labels: hydra

#571 cclib: 1.8.1b0 -> 1.8.1
  pkgs/python-by-name/cclib/package.nix
Labels: package update

#574 gauxc: init at unstable-2024-09-20
  overlay.nix
  pkgs/by-name/exchcxx/package.nix
  pkgs/by-name/gauxc/CmakeConfig.patch
  pkgs/by-name/gauxc/DynamicLinking.patch
  pkgs/by-name/gauxc/HighFive.patch
  pkgs/by-name/gauxc/Linalg.patch
  pkgs/by-name/gauxc/TestSerial.patch
  pkgs/by-name/gauxc/cmake.patch
  pkgs/by-name/gauxc/package.nix
  pkgs/by-name/integratorxx/package.nix
Labels: new package
