Repository Nix-QChem/NixOS-QChem, pull requests merged in 2024-11, with the labels that each got.

#576 orca: 6.0.0 -> 6.0.1
  pkgs/by-name/orca/package.nix
Labels: bug, package update

#578 Update flake.lock/package list
  flake.lock
  package_list.json
  package_list.md
Labels: hydra

#580 Update flake.lock/package list
  flake.lock
Labels: hydra

#581 Update flake.lock/package list
  flake.lock
Labels: hydra

#582 exciting: fluorine.0.0 -> neon.0.1
  pkgs/by-name/exciting/package.nix
Labels: package update

#584 Update flake.lock/package list
  flake.lock
Labels: hydra

#585 Update flake.lock/package list
  flake.lock
Labels: hydra
